name: ci

on:
  push:
    branches: [main, '**']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables for branch
        run: echo "Branch is ${{ github.ref }}"
        env:
          MONGO_URI_DEV: ${{ secrets.MONGO_URI_DEV }}
          MONGO_URI_PROD: ${{ secrets.MONGO_URI_PROD }}
          MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}

      - name: Run tests
        env:
          MONGO_URI_DEV: ${{ secrets.MONGO_URI_DEV }}
          MONGO_URI_PROD: ${{ secrets.MONGO_URI_PROD }}
          MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
        run: npm test
