name: Prevent Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    if: github.event.pusher.name != 'github-actions[bot]'
    steps:
      - name: Fail if not a PR merge from developer
        run: |
          echo "Direct pushes to main are not allowed. Please use Pull Requests from the developer branch."
          exit 1
